language: python
python:
 - "2.7"

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
 - sudo apt-get install ufraw-batch python-opencv
 - dpkg -L python-opencv
 - ln -s /usr/lib/python2.7/dist-packages/cv* $VIRTUAL_ENV/lib/python2.7/site-packages/
 - ls $VIRTUAL_ENV/lib/python2.7/site-packages/
 - pip install nose>=1.3.0
 - pip install coverage>=3.6
 - pip install coveralls

install:
 - ./install

script:
 - ./run_tests

after_script:
 - coveralls
